### ISSUE TITLE
Flawed regex

### ISSUE THREAD

**Issue by DrVilepis** [Testausserveri/env-exampler#2]
In the file src/index.js there is a regex, more accurately this one
> const envRegex = /(^[A-Z0-9_]+)(\=)(.*(\n)(?=[A-Z])|.*$)/gm;

this fails because environment variables can be any character, like for example
> töken="<token>"
This makes the script unusable, and a potential security flaw.

**Comment by lajp** [comment]
Perhaps use the regex from #1

**Comment by Esinko** [comment]
> This makes the script unusable, and a potential security flaw.

Could you give more details on how?
Also, please make a pull request with your fix and reference this issue.

**Comment by DrVilepis** [comment]
As I stated above, this may not sensor all environment variables as expected, since it only matches a small, seemingly arbitrary set of character.

**Comment by Esinko** [comment]
That makes sense. Feel free to implement a fix.
